# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site title and description
title:              DAPS Nexus
description:        a central repository of DAPS resources
lang:               en

# Site subpath, e.g. /blog
baseurl:            ""

# Permalink URLs structure, for permalink style options see: https://jekyllrb.com/docs/permalinks/
permalink:          /:title/

# Site base hostname & protocol, e.g. http://example.com
url:                "https://daps-pages.github.io"

# Site logo # e.g. logo.png, upload logo image file to /uploads/ folder
logo:

navbar:
    sticky:         true
    search:         true

# Default author settings
author:
    # name:           Feng Zhu
    # title:          Webmaster
    # avatar:

# Author settings, displayed on post and doc pages if front matter references author name e.g. author: peter
authors:
    fzhu:
      name:         Feng Zhu
      title:        Webmaster
      avatar:

# Social icons displayed in footer
social:
    email:
    website:
    facebook:
    flickr:
    dribbble:
    github:
    googleplus:
    instagram:
    linkedin:
    pinterest:
    twitter:
    vimeo:
    youtube:

# Share button
share:
    post:           true # Display share buttons on a post page
    doc:            true # Display share buttons on a doc page
    twitter:        username # Enable by adding Twitter handle
    facebook:       true # Enable by setting true (Facebook handle not required)

# Default footer image settings
footer:
    copyright:       © Copyright 2019, Paleoclimate Reanalyses, Data Assimilation and Proxy System modeling (DAPS) working group.

# Disqus comments shortname, requires Disqus account https://disqus.com/
disqus:
    shortname:      # 1234

# Google analytics code, get your code here https://www.google.com/analytics/
google_analytics:

# Number of posts displayed on blog page
paginate:           10

# Blog path
paginate_path:      "/blog/:num/"

# Path to post content assets directory i.e post images, pdfs etc
uploads:            /uploads/

# Build settings
markdown:           kramdown
highlighter:        rouge

gems:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-avatar
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules

sass:
  style:            compressed

collections:
  docs:
    output:         true
  faqs:
    output:         false
  changelogs:
    output:         false

# Defaults
defaults:
  # _posts
  - scope:
      path:         ""
      type:         posts
    values:
      layout:       post
  # _docs
  - scope:
      path:         ""
      type:         docs
    values:
      layout:       doc
